### ISSUE TITLE
Did something change about the stack image platform in the past two days?

### ISSUE THREAD

**Issue by josegonzalez** [heroku/cnb-builder-images#619] opened 2024-12-11 16:15 UTC
I run the Dokku PaaS and have a set of integration tests for our CNB support. One of those tests uses `heroku/builder:24` as the base image and and then installs the `python` packeto buildpack. This worked fine until yesterday at 7:33 AM EST, when I started seeing the following error:

```
#  !     ERROR: failed to build: downloading buildpack: extracting from registry 'gcr.io/paketo-buildpacks/python:2.22.3': fetching image: image with reference gcr.io/paketo-buildpacks/python:2.22.3 was found but its platform (linux) does not match the specified platform (linux/amd64)
```

I've checked with the packeto folks, and the os/arch of their image has been `linux` for a long time, so I'm wondering if something changed on the heroku side. Not sure if this should even be an issue - in my mind, that linux buildpack should work fine on a linux/amd64 platform, so maybe this is actually a CNB issue (lifecycle was released at 10:49 am yesterday, so seems unlikely).

Of note, I tried downgrading the packeto buildpack but still [see the issue](https://github.com/dokku/dokku/pull/7406), so I don't think anything changed there.

I'll also follow up in the CNB slack, but was posting here in case folks had a few ideas (I know the Fir stack is new, and I suspect if this is a larger issue with how buildpacks are published, folks are gonna smack into this at some point).

**Comment by edmorley** [comment] 2024-12-11 16:35
xref upstream CNB Slack discussion here:
https://cloud-native.slack.com/archives/C033DV8D9FB/p1733933958486749

**Comment by edmorley** [comment] 2024-12-13 22:04
Closing since the testing on the Slack thread confirmed an older version of the builder also had the same issue, so the cause must be something else.

**Closed by edmorley** 2024-12-13 22:04 UTC
